#The logo that will be used in every message of this plugin.
Logo: "[Alliances]"

#Changes the colors of all the messages to console and players.
ColorCodes:
  alertMessages: "&c"
  remarkMessages: "&a"
  infoMessages: "&e"
  
#All the configuration for handling coins
Coins:

  #The coins a player get on joining
  StarterCoins: 100
  
  #The coins it cost to create a alliance
  AllianceTypes:
    Cait Sith: 1000
    Gnome: 1000
    Imp: 1000
    Leprechaun: 1000
    Pooka: 1000
    Salamander: 1000
    Spriggan: 1000
    Sylph: 1000
    Undine: 1000 