#The logo that will be used in every message of this plugin.
Logo: "[Alliances]"

#Changes the colors of all the messages to console and players.
ColorCodes:
  alertMessages: "&c"
  remarkMessages: "&a"
  infoMessages: "&e"
  
#All the configuration for handling coins
Coins:

  #The coins a player get on joining
  StarterCoins: 100
  
  #The coins it cost to create a alliance
  AllianceTypes:
    Cait Sith: 1000
    Gnome: 1000
    Imp: 1000
    Leprechaun: 1000
    Pooka: 1000
    Salamander: 1000
    Spriggan: 1000
    Sylph: 1000
    Undine: 1000 
  
  Town_Starter_Cost: 10000
  Town_Claim_Cost: 150
    
Outpost:
  # the time per reward (in seconds) and the time it takes to take over a outpost (in sec) (best to take a number divisible by 4)
  Time_Per_Reward: 40
  Coin_Reward: 50
  Exp_Per_Reward: 50
        
Town:
  Town_Claim_Limit: 100        

#Configurations for chat. var: {%alli_name%, %player_name%, %alli_rank%}
Chat:
  Message: "%alli_name% %player_name% %alli_rank%>"
  
SQL:
  enable: false
  ip: "localhost:3306"
  username: "root"
  password: "root"
  dbName: "minecraft"





    
