#The logo that will be used in every message of this plugin.
Logo: "[Alliances]"

#Changes the colors of all the messages to console and players.
ColorCodes:
  alertMessages: "&c"
  remarkMessages: "&a"
  infoMessages: "&e"
  
#All the configuration for handling coins
Coins:

  #The coins a player get on joining
  StarterCoins: 100
  
  #The coins it cost to create a alliance
  AllianceTypes:
    Cait Sith: 1000
    Gnome: 1000
    Imp: 1000
    Leprechaun: 1000
    Pooka: 1000
    Salamander: 1000
    Spriggan: 1000
    Sylph: 1000
    Undine: 1000 
  
  Town_Starter_Cost: 10000
  Town_Claim_Cost: 150
    
Outpost:
  # the time per reward (in seconds) and the time it takes to take over a outpost (in sec) (best to take a number divisible by 4)
  Time_Per_Reward: 40
  Coin_Reward: 50
  
  Exp_Per_Reward: 10
  
  Rewards:
    Blacksmith:
      "1":
        ID: 1
        Amount: 10
        Data: 0
        Percentage: 100
    Dock:
      "1":
        ID: 1
        Amount: 10
        Data: 0
        Percentage: 100
    Farm:
      "1":
        ID: 1
        Amount: 10
        Data: 0
        Percentage: 100
    God:
      "1":
        ID: 1
        Amount: 10
        Data: 0
        Percentage: 100
    Magic_Tower:
      "1":
        ID: 1
        Amount: 10
        Data: 0
        Percentage: 100
    Mine:
      "1":
        ID: 1
        Amount: 10
        Data: 0
        Percentage: 100
    Mob_Farm:
      "1":
        ID: 1
        Amount: 10
        Data: 0
        Percentage: 100
        
        
Town:
  Town_Claim_Limit: 100        

#Configurations for chat. var: {%alli_name%, %player_name%, %alli_rank%}
Chat:
  Message: "%alli_name% %player_name% %alli_rank%>"
  
Level:
  Amount_Exp:
    2: 120
    3: 300
    4: 480
    5: 690
    6: 930
    7: 1300
    8: 1600
    9: 1930
    10: 2290
    11: 2680
    12: 3000
    13: 3400
    14: 3950
    15: 4675
    16: 5230
    17: 5920
    18: 6960
    19: 8230
    20: 9500
    21: 11000
    22: 13000
    23: 17000
    24: 25000
    25: 35000
    26: 50000
    27: 75000
    28: 125000
    29: 200000
    30: 400000





    
