#The logo that will be used in every message of this plugin.
Logo: "[Alliances]"

#Changes the colors of all the messages to console and players.
ColorCodes:
  alertMessages: "&c"
  remarkMessages: "&a"
  infoMessages: "&e"
  
#All the configuration for handling coins
Coins:

  #The coins a player get on joining
  StarterCoins: 100
  
  #The coins it cost to create a alliance
  AllianceTypes:
    Cait Sith: 1000
    Gnome: 1000
    Imp: 1000
    Leprechaun: 1000
    Pooka: 1000
    Salamander: 1000
    Spriggan: 1000
    Sylph: 1000
    Undine: 1000 
    
    
Outpost:
  # the time per reward (in seconds) and the time it takes to take over a outpost (in sec) (best to take a number divisible by 4)
  Time_Per_Reward: 240
  Time_For_Take_Over: 600
  
  Rewards:
    Blacksmith:
      "1":
        ID: 1
        Amount: 10
        Data: 0
    Dock:
      "1":
        ID: 1
        Amount: 10
        Data: 0
    Farm:
      "1":
        ID: 1
        Amount: 10
        Data: 0
      Rewards:
    God:
      "1":
        ID: 1
        Amount: 10
        Data: 0
    Magic_Tower:
      "1":
        ID: 1
        Amount: 10
        Data: 0
    Mine:
      "1":
        ID: 1
        Amount: 10
        Data: 0
    Mob_Farm:
      "1":
        ID: 1
        Amount: 10
        Data: 0