#The logo that will be used in every message of this plugin.
Logo: "[Alliances]"

#Changes the colors of all the messages to console and players.
ColorCodes:
  alertMessages: "&c"
  remarkMessages: "&a"
  infoMessages: "&e"
  
#All the configuration for handling coins
Coins:

  #The coins a player get on joining
  StarterCoins: 100
  
  #The coins it cost to create a alliance
  Dark: 
    SmallAllianceCost: 1000
    NormalAllianceCost: 2000
    BigAllianceCost: 3000
    HugeAllianceCost: 4000
  Light:
    SmallAllianceCost: 1000
    NormalAllianceCost: 2000
    BigAllianceCost: 3000
    HugeAllianceCost: 4000