main: me.Haeseke1.Alliances.Main.Main
version: 1.0
name: Alliances
authors: [KingPieter, Haeseke1]

commands:
  alliances:
    aliases: [alli,al]
  coin:
    aliases: [c,money,coins]
  Shop:
    aliases: [sh]
  Outpost:
    aliases: [outp]
  terrain:
    aliases: [ter]
  Challenges:
    aliases: [ch,chal]
  Arena:
    aliases: [a]
  Town: 
    aliases: [t]