main: me.Haeseke1.Alliances.Main.Main
version: 1.0
name: Alliances
authors: [KingPieter, Haeseke1]

commands:
  alliances:
    aliases: [alli,al]
  coin:
    aliases: [c,money,coins]
  Shop:
    aliases: [sh]
  Outpost:
    aliases: [outp]
  terrain:
    aliases: [ter]
  Challenges:
    aliases: [ch,chal]
  Arena:
    aliases: [a]
  Town: 
    aliases: [t]
  Mount:
    aliases: [mount,m]
  PVE:
  Building:
    aliases: [b,build]
  Items:
    aliases: [it,i,item]
  Wand:
    aliases: [w,wand]
  Crate:
    aliases: [c,cr,crates]
  Auction:
    aliases: [auc,auction,ah]
  Portal:
    aliases: [portal,p]
  Rewards:
    aliases: [rewards,reward]
  Voteset:
    aliases: [voteset]